vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        picture_file:
            uri_prefix:         '%app.path.picture_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.picture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
